### ISSUE TITLE
Timeline for full DE implementation in Python

### ISSUE THREAD

**Issue by krademaker** [const-ae/pyLemur#2]
### Description of feature

Hi Constantin,

I really like your method and previously glmGamPoi and am happy to see a Python implementation as well. I am curious to know what the expected timeline is to implement all DE testing functionality from the R package to Python?

It would be great to incorporate Lemur into the AnnData / scVerse framework without relying too much on reticulate and R-to-Python switching for workflows, hence the curiosity.

I look forward to hearing from you and in case you are looking for testers.

Best,
Koen

**Comment by const-ae** [comment]
Hi Koen,

thanks for your interest in pyLemur :)

>  I am curious to know what the expected timeline is to implement all DE testing functionality from the R package to Python?

To be honest, I hadn't had plans to get both packages to feature parity in the near future. One issue is that the differential expression test for the count data needs to adjust the size factors for each gene. `edgeR` and `glmGamPoi` support this in R, but I don't think there is any Python implementation available that can do this yet. As an alternative to the count-based test, lemur uses limma, and I am not sure if there's anything equivalent in Python either.

However, if there's demand, I might reconsider and see what I can do; so, in that sense feedback such as your's is very useful for me to prioritize the work :)

**Comment by krademaker** [comment]
Thanks for the clarification on that, Constantin! I think that for now I will invest some time in setting up a good mamba environment to deal with both language and data formats to use the R-implementation of Lemur. If in the future there will be more development on the Python version I would definitely be happy to know! Best, Koen
